version: 2
project_name: issue-agent

git:
  tag_sort: -version:creatordate

builds:
  - id: runner
    dir: agent
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: ./cmd/runner/main.go
    binary: issue-agent
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-X main.containerImageTag={{.Tag}}"
  - id: agent
    dir: agent
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: ./cmd/agent/main.go
    binary: agent
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-X github.com/clover0/issue-agent/cli.version={{ .Tag }}"

dockers:
  - id: issue-agent-amd64
    image_templates:
      - "ghcr.io/clover0/issue-agent-amd64:{{ .Tag }}"
    ids:
      - agent
    use: buildx
    goos: linux
    goarch: amd64
    dockerfile: agent/release.Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.description={{.ProjectName}}"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - id: issue-agent-arm64
    image_templates:
      - "ghcr.io/clover0/issue-agent-arm64v8:{{ .Tag }}"
    ids:
      - agent
    use: buildx
    goos: linux
    goarch: arm64
    dockerfile: agent/release.Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.description={{.ProjectName}}"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

docker_manifests:
  - name_template: "ghcr.io/clover0/issue-agent:{{ .Tag }}"
    id: issue-agent-manifest
    image_templates:
      - "ghcr.io/clover0/issue-agent-amd64:{{ .Tag }}"
      - "ghcr.io/clover0/issue-agent-arm64v8:{{ .Tag }}"

signs:
  - cmd: cosign
    artifacts: checksum
    certificate: ${artifact}.pem
    signature: ${artifact}.sig
    args:
      - "sign-blob"
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "--oidc-provider"
      - "github"
      - "${artifact}"
      - "--yes"

docker_signs:
  - cmd: cosign
    ids:
      - issue-agent-manifest
    artifacts: manifests
    args:
      - "sign"
      - "${artifact}"
      - "--yes"

archives:
  - format: tar.gz
    builds:
      - runner
    name_template: >-
      {{ .Binary }}_{{ .Os }}_{{ .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

release:
  prerelease: auto
  replace_existing_draft: true
  replace_existing_artifacts: true

brews:
  - name: "{{ .ProjectName }}"
    skip_upload: auto
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    repository:
      owner: clover0
      name: homebrew-issue-agent
      token: "{{ .Env.HOMEBREW_GITHUB_TOKEN }}"
    test: |
      system "#{bin}/issue-agent version"
