FROM python:3.13-slim-bookworm@sha256:026dd417a88d0be8ed5542a05cff5979d17625151be8a1e25a994f85c87962a5

RUN pip install mkdocs
RUN pip install mkdocs-material
RUN pip install mkdocs-minify-plugin
RUN pip install mkdocs-redirects
